<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <AssemblyName>RedMRpUtility</AssemblyName>
    <RootNamespace>RedMRpUtility</RootNamespace>
    <Version>2.1.1</Version>
    <Copyright>Copyright (c) 2026 HE4THER DEV</Copyright>
    <Company>HE4THER DEV</Company>
    <Product>RedM RP Utility</Product>
    <Description>Hub TeamSpeak SaltyChat / Cache RedM</Description>
    <AssemblyTitle>RedM RP Utility</AssemblyTitle>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Assets\app.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Assets\app-icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Assets\background_redm.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="Assets\background_redm.png">
      <LogicalName>RedMRpUtility.Assets.background_redm.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <Target Name="CopyAssetsToPublish" AfterTargets="Publish">
    <MakeDir Directories="$(PublishDir)Assets" />
    <ItemGroup>
      <_PublishAssets Include="Assets\app.ico;Assets\app-icon.png;Assets\background_redm.png" />
    </ItemGroup>
    <Copy SourceFiles="@(_PublishAssets)" DestinationFolder="$(PublishDir)Assets" SkipUnchangedFiles="true" />
  </Target>
</Project>
